"""Install pinned Linux CPU engines into the project's mounted data disk.

No sudo, package-manager action, YAML mutation, overwriting, or service restart.
Example: .venv/bin/python tools/install_board_engines.py --proxy http://127.0.0.1:7890
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import platform
import re
import shutil
import stat
import subprocess
import tempfile
import time
import urllib.parse
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parents[1]
XQ_TAG = "xiangqi-c07e94a5c7cb"
GO_TAG = "1.16.3"
MODEL = "g170e-b10c128-s1141046784-d204142634.bin.gz"
XQ_SOURCE = "84dd49a4bd00b9959b07e1b917d362c46e6f6d75"
XQ_BASE = f"https://github.com/fairy-stockfish/Fairy-Stockfish-NNUE/releases/download/{XQ_TAG}/"
GO_BASE = f"https://github.com/lightvector/KataGo/releases/download/v{GO_TAG}/"
# Engine digests from the official GitHub release asset metadata. Model digest
# independently computed from the official archive over HTTPS, 2026-09-28.
ASSETS = {
    "fairy-avx2": (XQ_BASE + "fairy-stockfish_x86-64-avx2", "df70c56d5f5d7b7b65aeef0fe12dfd156a1645f44f0e554d26b76dbaf5f2e98e"),
    "fairy-generic": (XQ_BASE + "fairy-stockfish_x86-64", "2394fd4d1430edfddaea55097a7e10c8a9b96fca94f5600a8fb6e209b769bf01"),
    "katago-avx2": (GO_BASE + "katago-v1.16.3-eigenavx2-linux-x64.zip", "c14e4199318b33d2257bc7177fc65ac5081e9ce5a002bfbc00be1594f6f1f6ec"),
    "katago-generic": (GO_BASE + "katago-v1.16.3-eigen-linux-x64.zip", "8b617286e3fc778e69feeae470c994efaca08865a3edb497a5d41a60be36c6a8"),
    "model": ("https://katagoarchive.org/g170/neuralnets/" + MODEL, "1a8e05a4ea3fca20dab79410cbb566c760767fcdd2fa0b701cfe259a84cc8b04"),
}
GO_CONFIG = """# Generated by QQ bot's pinned local-engine installer.
rules = chinese-ogs
numSearchThreads = 1
numEigenThreadsPerModel = 1
numNNServerThreadsPerModel = 1
nnMaxBatchSize = 1
nnCacheSizePowerOfTwo = 14
nnMutexPoolSizePowerOfTwo = 10
ponderingEnabled = false
allowResignation = false
resignThreshold = -0.90
resignConsecTurns = 3
maxVisits = 16
maxTime = 0.5
chosenMoveTemperature = 0.8
chosenMoveTemperatureEarly = 0.8
logAllGTPCommunication = false
logSearchInfo = false
logSearchInfoForChosenMove = false
logToStderr = false
"""


def download(opener, url, target, expected=None, maximum=256 * 1024 * 1024):
    if urllib.parse.urlparse(url).scheme != "https":
        raise ValueError("Only HTTPS downloads are allowed")
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 QQBotEngineInstaller/1.0"})
    digest, total = hashlib.sha256(), 0
    with opener.open(request, timeout=30) as response, target.open("xb") as output:
        if urllib.parse.urlparse(response.url).scheme != "https":
            raise ValueError("Refusing insecure download redirect")
        started = time.monotonic()
        while True:
            chunk = response.read(1024 * 1024)
            if not chunk:
                break
            total += len(chunk)
            if total > maximum or time.monotonic() - started > 600:
                raise ValueError("Download exceeded size/time limit")
            output.write(chunk)
            digest.update(chunk)
    actual = digest.hexdigest()
    if not total or (expected is not None and actual != expected):
        raise ValueError(f"SHA256 mismatch or empty file: {target.name}")
    return {"url": url, "sha256": actual, "bytes": total}


def extract_safe(archive, target):
    with zipfile.ZipFile(archive) as packed:
        if len(packed.infolist()) > 2000 or sum(item.file_size for item in packed.infolist()) > 512 * 1024 * 1024:
            raise ValueError("Oversized engine archive")
        for item in packed.infolist():
            name = PurePosixPath(item.filename.replace("\\", "/"))
            mode = item.external_attr >> 16
            if name.is_absolute() or ".." in name.parts:
                raise ValueError("Unsafe archive path")
            if ":" in str(name) or stat.S_ISLNK(mode):
                raise ValueError("Unsafe archive member")
            path = target.joinpath(*name.parts)
            if not path.resolve().is_relative_to(target.resolve()):
                raise ValueError("Archive escapes staging directory")
            if item.is_dir():
                path.mkdir(parents=True, exist_ok=True)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                with packed.open(item) as source, path.open("xb") as output:
                    shutil.copyfileobj(source, output)


def preflight(root):
    if platform.system() != "Linux" or platform.machine().lower() not in ("x86_64", "amd64"):
        raise ValueError("This installer is for Linux x86_64; do not install these binaries on another architecture")
    data = root / "data"
    check = subprocess.run(["findmnt", "--mountpoint", str(data), "--noheadings", "--output", "TARGET"],
                           capture_output=True, text=True, timeout=5, check=False)
    if check.returncode or not check.stdout.strip():
        raise ValueError("data is not a mountpoint; mount the data disk first (installer will not change mounts)")
    if shutil.disk_usage(data).free < 512 * 1024 * 1024:
        raise ValueError("Need at least 512 MiB free on the data disk")
    mem = Path("/proc/meminfo").read_text(encoding="ascii")
    available = re.search(r"^MemAvailable:\s+(\d+)\s+kB$", mem, re.M)
    if not available or int(available[1]) < 600 * 1024:
        raise ValueError("Less than 600 MiB available memory; stop and inspect memory pressure before installing")
    cpu = Path("/proc/cpuinfo").read_text(encoding="ascii")
    flags = re.findall(r"^flags\s*:\s*(.*)$", cpu, re.M)
    avx2 = bool(flags) and all({"avx", "avx2", "fma"} <= set(row.split()) for row in flags)
    return "avx2" if avx2 else "generic"


def install_game(root, game, architecture, opener):
    if game == "xiangqi":
        parent, version = root / "data/engines/fairy-stockfish", XQ_TAG
    else:
        parent, version = root / "data/engines/katago", GO_TAG
    allowed = (root / "data").resolve()
    if not parent.resolve().is_relative_to(allowed):
        raise ValueError("Engine directory resolves outside the data disk")
    parent.mkdir(parents=True, exist_ok=True)
    target = parent / version
    if target.exists() or target.is_symlink():
        raise ValueError(f"Target already exists; refusing to overwrite: {target}")
    stage = Path(tempfile.mkdtemp(prefix=".install-" + version + "-", dir=parent))
    sources = []
    try:
        if game == "xiangqi":
            url, digest = ASSETS["fairy-" + architecture]
            sources.append(download(opener, url, stage / "fairy-stockfish", digest))
            (stage / "fairy-stockfish").chmod(0o755)
            license_url = f"https://raw.githubusercontent.com/fairy-stockfish/Fairy-Stockfish-NNUE/{XQ_TAG}/Copying.txt"
            sources.append(download(opener, license_url, stage / "LICENSE-engine-and-network.txt", maximum=1024 * 1024))
            sources.append({"source_revision": XQ_SOURCE, "built_in_network": XQ_TAG + ".nnue",
                            "source_url": f"https://github.com/fairy-stockfish/Fairy-Stockfish/tree/{XQ_SOURCE}"})
        else:
            url, digest = ASSETS["katago-" + architecture]
            archive = stage / "release.zip"
            sources.append(download(opener, url, archive, digest))
            extract_safe(archive, stage / "release")
            binaries = [p for p in (stage / "release").rglob("katago") if p.is_file()]
            if len(binaries) != 1:
                raise ValueError("Expected exactly one KataGo binary in the archive")
            shutil.copy2(binaries[0], stage / "katago")
            (stage / "katago").chmod(0o755)
            url, digest = ASSETS["model"]
            sources.append(download(opener, url, stage / MODEL, digest))
            sources.append(download(opener, f"https://raw.githubusercontent.com/lightvector/KataGo/v{GO_TAG}/LICENSE",
                                    stage / "LICENSE-engine.txt", maximum=1024 * 1024))
            sources.append(download(opener, "https://katagoarchive.org/g170/LICENSE.txt",
                                    stage / "LICENSE-network.txt", maximum=1024 * 1024))
            (stage / "minigames.cfg").write_text(GO_CONFIG, encoding="utf-8")
        manifest = {"game": game, "version": version, "architecture": architecture,
                    "installed_at": datetime.now(timezone.utc).isoformat(), "sources": sources}
        (stage / "INSTALL.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        if target.exists() or target.is_symlink():
            raise ValueError("Target was created concurrently; refusing to replace it")
        stage.rename(target)
        print(f"Installed {game}: {target}")
    except BaseException:
        # Leave only the private staging directory for diagnosis; never remove
        # pre-existing data or print a false success message.
        print(f"Installation did not complete. Staging files retained: {stage}")
        raise


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--game", choices=("all", "xiangqi", "go"), default="all")
    parser.add_argument("--proxy", help="HTTP proxy, e.g. http://127.0.0.1:7890; credentials are never logged")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        arch = preflight(root)
        if args.proxy:
            if urllib.parse.urlparse(args.proxy).scheme not in ("http", "https"):
                raise ValueError("Use an HTTP(S) proxy URL")
            opener = urllib.request.build_opener(urllib.request.ProxyHandler({"http": args.proxy, "https": args.proxy}))
        else:
            opener = urllib.request.build_opener()
        print(f"Linux x86_64 CPU package: {arch}. Data mount and available memory verified.")
        for game in (("xiangqi", "go") if args.game == "all" else (args.game,)):
            install_game(root, game, arch, opener)
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        # Avoid dumping proxy credentials or environment variables in tracebacks.
        print(f"STOP: {type(exc).__name__}: installation failed; inspect the preceding checked-path message.")
        if isinstance(exc, ValueError):
            print(str(exc))
        return 1
    print("Files installed only. Enable minigames.xiangqi.engine / go.engine in server config, then run tools/check_board_engines.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
